//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAHorseApiModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FindAHorseBoxDbEntities : DbContext
    {
        public FindAHorseBoxDbEntities()
            : base("name=FindAHorseBoxDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBookingMaster> tblBookingMasters { get; set; }
        public virtual DbSet<tblHorseBox> tblHorseBoxes { get; set; }
        public virtual DbSet<tblHorseBoxImage> tblHorseBoxImages { get; set; }
        public virtual DbSet<tblHorseImage> tblHorseImages { get; set; }
        public virtual DbSet<tblHors> tblHorses { get; set; }
        public virtual DbSet<tblRamp> tblRamps { get; set; }
        public virtual DbSet<tblUserMapper> tblUserMappers { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
