//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAHorseApiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingMaster
    {
        public int BookingId { get; set; }
        public Nullable<int> BookedBy { get; set; }
        public Nullable<int> BookedHorseBox { get; set; }
        public Nullable<System.DateTime> BookedOn { get; set; }
    
        public virtual tblHorseBox tblHorseBox { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
