//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAHorseApiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMapper
    {
        public int UserId { get; set; }
        public int UserTypeId { get; set; }
        public int UserMapperId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUserType tblUserType { get; set; }
    }
}
